import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { MantineProvider, ColorSchemeScript } from '@mantine/core';
import { Notifications } from '@mantine/notifications';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { RouterProvider, createRouter } from '@tanstack/react-router';
import { routeTree } from './routeTree.gen'; // auto-generated by TanStack Router
import { theme } from './theme';
import { tauriStore } from '@/lib/tauriStore';
import { useAuthStore } from '@/store/authStore';
import { useSettingsStore } from '@/store/settingsStore';
// Note: @/api/client is imported dynamically inside rehydrate() to avoid circular deps
import '@mantine/core/styles.css';
import '@mantine/notifications/styles.css';
import '@mantine/dates/styles.css';

const queryClient = new QueryClient();
const router = createRouter({ routeTree, context: { queryClient } });

// Declare router type for TanStack Router type safety
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router;
  }
}

async function rehydrate(): Promise<void> {
  // Import reinitialiseClient here to avoid a top-level circular dependency
  // between client.ts and settingsStore.ts (see §4 for full explanation).
  const { reinitialiseClient } = await import('@/api/client');

  // 1. Server URL — must be first so ky is ready before any API call
  const savedUrl = await tauriStore.get<string>('serverBaseUrl');
  const baseUrl = savedUrl ?? '';
  useSettingsStore.getState().setServerBaseUrl(baseUrl);
  reinitialiseClient(baseUrl);

  // 2. Auth tokens
  const accessToken = await tauriStore.get<string>('accessToken');
  const refreshToken = await tauriStore.get<string>('refreshToken');
  if (accessToken && refreshToken) {
    useAuthStore.getState().setTokens({ accessToken, refreshToken });
  }
}

rehydrate().then(() => {
  createRoot(document.getElementById('root')!).render(
    <StrictMode>
      <QueryClientProvider client={queryClient}>
        <MantineProvider theme={theme} defaultColorScheme="auto">
          <ColorSchemeScript defaultColorScheme="auto" />
          <Notifications position="top-right" autoClose={4000} />
          <RouterProvider router={router} />
        </MantineProvider>
      </QueryClientProvider>
    </StrictMode>
  );
});
