/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HouseholdsIndexRouteImport } from './routes/households/index'
import { Route as HouseholdsNewRouteImport } from './routes/households/new'
import { Route as HouseholdsHidRouteRouteImport } from './routes/households/$hid/route'
import { Route as HouseholdsHidSettingsRouteImport } from './routes/households/$hid/settings'
import { Route as HouseholdsHidOverviewRouteImport } from './routes/households/$hid/overview'
import { Route as HouseholdsHidArchiveRouteImport } from './routes/households/$hid/archive'
import { Route as HouseholdsHidItemsIndexRouteImport } from './routes/households/$hid/items/index'
import { Route as HouseholdsHidFreezersFidRouteImport } from './routes/households/$hid/freezers/$fid'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdsIndexRoute = HouseholdsIndexRouteImport.update({
  id: '/households/',
  path: '/households/',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdsNewRoute = HouseholdsNewRouteImport.update({
  id: '/households/new',
  path: '/households/new',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdsHidRouteRoute = HouseholdsHidRouteRouteImport.update({
  id: '/households/$hid',
  path: '/households/$hid',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdsHidSettingsRoute = HouseholdsHidSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => HouseholdsHidRouteRoute,
} as any)
const HouseholdsHidOverviewRoute = HouseholdsHidOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => HouseholdsHidRouteRoute,
} as any)
const HouseholdsHidArchiveRoute = HouseholdsHidArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => HouseholdsHidRouteRoute,
} as any)
const HouseholdsHidItemsIndexRoute = HouseholdsHidItemsIndexRouteImport.update({
  id: '/items/',
  path: '/items/',
  getParentRoute: () => HouseholdsHidRouteRoute,
} as any)
const HouseholdsHidFreezersFidRoute =
  HouseholdsHidFreezersFidRouteImport.update({
    id: '/freezers/$fid',
    path: '/freezers/$fid',
    getParentRoute: () => HouseholdsHidRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/households/$hid': typeof HouseholdsHidRouteRouteWithChildren
  '/households/new': typeof HouseholdsNewRoute
  '/households/': typeof HouseholdsIndexRoute
  '/households/$hid/archive': typeof HouseholdsHidArchiveRoute
  '/households/$hid/overview': typeof HouseholdsHidOverviewRoute
  '/households/$hid/settings': typeof HouseholdsHidSettingsRoute
  '/households/$hid/freezers/$fid': typeof HouseholdsHidFreezersFidRoute
  '/households/$hid/items/': typeof HouseholdsHidItemsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/households/$hid': typeof HouseholdsHidRouteRouteWithChildren
  '/households/new': typeof HouseholdsNewRoute
  '/households': typeof HouseholdsIndexRoute
  '/households/$hid/archive': typeof HouseholdsHidArchiveRoute
  '/households/$hid/overview': typeof HouseholdsHidOverviewRoute
  '/households/$hid/settings': typeof HouseholdsHidSettingsRoute
  '/households/$hid/freezers/$fid': typeof HouseholdsHidFreezersFidRoute
  '/households/$hid/items': typeof HouseholdsHidItemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/households/$hid': typeof HouseholdsHidRouteRouteWithChildren
  '/households/new': typeof HouseholdsNewRoute
  '/households/': typeof HouseholdsIndexRoute
  '/households/$hid/archive': typeof HouseholdsHidArchiveRoute
  '/households/$hid/overview': typeof HouseholdsHidOverviewRoute
  '/households/$hid/settings': typeof HouseholdsHidSettingsRoute
  '/households/$hid/freezers/$fid': typeof HouseholdsHidFreezersFidRoute
  '/households/$hid/items/': typeof HouseholdsHidItemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/profile'
    | '/register'
    | '/households/$hid'
    | '/households/new'
    | '/households/'
    | '/households/$hid/archive'
    | '/households/$hid/overview'
    | '/households/$hid/settings'
    | '/households/$hid/freezers/$fid'
    | '/households/$hid/items/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile'
    | '/register'
    | '/households/$hid'
    | '/households/new'
    | '/households'
    | '/households/$hid/archive'
    | '/households/$hid/overview'
    | '/households/$hid/settings'
    | '/households/$hid/freezers/$fid'
    | '/households/$hid/items'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/profile'
    | '/register'
    | '/households/$hid'
    | '/households/new'
    | '/households/'
    | '/households/$hid/archive'
    | '/households/$hid/overview'
    | '/households/$hid/settings'
    | '/households/$hid/freezers/$fid'
    | '/households/$hid/items/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  HouseholdsHidRouteRoute: typeof HouseholdsHidRouteRouteWithChildren
  HouseholdsNewRoute: typeof HouseholdsNewRoute
  HouseholdsIndexRoute: typeof HouseholdsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/households/': {
      id: '/households/'
      path: '/households'
      fullPath: '/households/'
      preLoaderRoute: typeof HouseholdsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/households/new': {
      id: '/households/new'
      path: '/households/new'
      fullPath: '/households/new'
      preLoaderRoute: typeof HouseholdsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/households/$hid': {
      id: '/households/$hid'
      path: '/households/$hid'
      fullPath: '/households/$hid'
      preLoaderRoute: typeof HouseholdsHidRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/households/$hid/settings': {
      id: '/households/$hid/settings'
      path: '/settings'
      fullPath: '/households/$hid/settings'
      preLoaderRoute: typeof HouseholdsHidSettingsRouteImport
      parentRoute: typeof HouseholdsHidRouteRoute
    }
    '/households/$hid/overview': {
      id: '/households/$hid/overview'
      path: '/overview'
      fullPath: '/households/$hid/overview'
      preLoaderRoute: typeof HouseholdsHidOverviewRouteImport
      parentRoute: typeof HouseholdsHidRouteRoute
    }
    '/households/$hid/archive': {
      id: '/households/$hid/archive'
      path: '/archive'
      fullPath: '/households/$hid/archive'
      preLoaderRoute: typeof HouseholdsHidArchiveRouteImport
      parentRoute: typeof HouseholdsHidRouteRoute
    }
    '/households/$hid/items/': {
      id: '/households/$hid/items/'
      path: '/items'
      fullPath: '/households/$hid/items/'
      preLoaderRoute: typeof HouseholdsHidItemsIndexRouteImport
      parentRoute: typeof HouseholdsHidRouteRoute
    }
    '/households/$hid/freezers/$fid': {
      id: '/households/$hid/freezers/$fid'
      path: '/freezers/$fid'
      fullPath: '/households/$hid/freezers/$fid'
      preLoaderRoute: typeof HouseholdsHidFreezersFidRouteImport
      parentRoute: typeof HouseholdsHidRouteRoute
    }
  }
}

interface HouseholdsHidRouteRouteChildren {
  HouseholdsHidArchiveRoute: typeof HouseholdsHidArchiveRoute
  HouseholdsHidOverviewRoute: typeof HouseholdsHidOverviewRoute
  HouseholdsHidSettingsRoute: typeof HouseholdsHidSettingsRoute
  HouseholdsHidFreezersFidRoute: typeof HouseholdsHidFreezersFidRoute
  HouseholdsHidItemsIndexRoute: typeof HouseholdsHidItemsIndexRoute
}

const HouseholdsHidRouteRouteChildren: HouseholdsHidRouteRouteChildren = {
  HouseholdsHidArchiveRoute: HouseholdsHidArchiveRoute,
  HouseholdsHidOverviewRoute: HouseholdsHidOverviewRoute,
  HouseholdsHidSettingsRoute: HouseholdsHidSettingsRoute,
  HouseholdsHidFreezersFidRoute: HouseholdsHidFreezersFidRoute,
  HouseholdsHidItemsIndexRoute: HouseholdsHidItemsIndexRoute,
}

const HouseholdsHidRouteRouteWithChildren =
  HouseholdsHidRouteRoute._addFileChildren(HouseholdsHidRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  HouseholdsHidRouteRoute: HouseholdsHidRouteRouteWithChildren,
  HouseholdsNewRoute: HouseholdsNewRoute,
  HouseholdsIndexRoute: HouseholdsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
