/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedHouseholdsIndexRouteImport } from './routes/_authenticated/households/index'
import { Route as AuthenticatedHouseholdsNewRouteImport } from './routes/_authenticated/households/new'
import { Route as AuthenticatedHouseholdsHidRouteRouteImport } from './routes/_authenticated/households/$hid/route'
import { Route as AuthenticatedHouseholdsHidSettingsRouteImport } from './routes/_authenticated/households/$hid/settings'
import { Route as AuthenticatedHouseholdsHidOverviewRouteImport } from './routes/_authenticated/households/$hid/overview'
import { Route as AuthenticatedHouseholdsHidArchiveRouteImport } from './routes/_authenticated/households/$hid/archive'
import { Route as AuthenticatedHouseholdsHidMealPlansIndexRouteImport } from './routes/_authenticated/households/$hid/meal-plans/index'
import { Route as AuthenticatedHouseholdsHidItemsIndexRouteImport } from './routes/_authenticated/households/$hid/items/index'
import { Route as AuthenticatedHouseholdsHidFreezersFidRouteImport } from './routes/_authenticated/households/$hid/freezers/$fid'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHouseholdsIndexRoute =
  AuthenticatedHouseholdsIndexRouteImport.update({
    id: '/households/',
    path: '/households/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHouseholdsNewRoute =
  AuthenticatedHouseholdsNewRouteImport.update({
    id: '/households/new',
    path: '/households/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHouseholdsHidRouteRoute =
  AuthenticatedHouseholdsHidRouteRouteImport.update({
    id: '/households/$hid',
    path: '/households/$hid',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHouseholdsHidSettingsRoute =
  AuthenticatedHouseholdsHidSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedHouseholdsHidRouteRoute,
  } as any)
const AuthenticatedHouseholdsHidOverviewRoute =
  AuthenticatedHouseholdsHidOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AuthenticatedHouseholdsHidRouteRoute,
  } as any)
const AuthenticatedHouseholdsHidArchiveRoute =
  AuthenticatedHouseholdsHidArchiveRouteImport.update({
    id: '/archive',
    path: '/archive',
    getParentRoute: () => AuthenticatedHouseholdsHidRouteRoute,
  } as any)
const AuthenticatedHouseholdsHidMealPlansIndexRoute =
  AuthenticatedHouseholdsHidMealPlansIndexRouteImport.update({
    id: '/meal-plans/',
    path: '/meal-plans/',
    getParentRoute: () => AuthenticatedHouseholdsHidRouteRoute,
  } as any)
const AuthenticatedHouseholdsHidItemsIndexRoute =
  AuthenticatedHouseholdsHidItemsIndexRouteImport.update({
    id: '/items/',
    path: '/items/',
    getParentRoute: () => AuthenticatedHouseholdsHidRouteRoute,
  } as any)
const AuthenticatedHouseholdsHidFreezersFidRoute =
  AuthenticatedHouseholdsHidFreezersFidRouteImport.update({
    id: '/freezers/$fid',
    path: '/freezers/$fid',
    getParentRoute: () => AuthenticatedHouseholdsHidRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/households/$hid': typeof AuthenticatedHouseholdsHidRouteRouteWithChildren
  '/households/new': typeof AuthenticatedHouseholdsNewRoute
  '/households/': typeof AuthenticatedHouseholdsIndexRoute
  '/households/$hid/archive': typeof AuthenticatedHouseholdsHidArchiveRoute
  '/households/$hid/overview': typeof AuthenticatedHouseholdsHidOverviewRoute
  '/households/$hid/settings': typeof AuthenticatedHouseholdsHidSettingsRoute
  '/households/$hid/freezers/$fid': typeof AuthenticatedHouseholdsHidFreezersFidRoute
  '/households/$hid/items/': typeof AuthenticatedHouseholdsHidItemsIndexRoute
  '/households/$hid/meal-plans/': typeof AuthenticatedHouseholdsHidMealPlansIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/households/$hid': typeof AuthenticatedHouseholdsHidRouteRouteWithChildren
  '/households/new': typeof AuthenticatedHouseholdsNewRoute
  '/households': typeof AuthenticatedHouseholdsIndexRoute
  '/households/$hid/archive': typeof AuthenticatedHouseholdsHidArchiveRoute
  '/households/$hid/overview': typeof AuthenticatedHouseholdsHidOverviewRoute
  '/households/$hid/settings': typeof AuthenticatedHouseholdsHidSettingsRoute
  '/households/$hid/freezers/$fid': typeof AuthenticatedHouseholdsHidFreezersFidRoute
  '/households/$hid/items': typeof AuthenticatedHouseholdsHidItemsIndexRoute
  '/households/$hid/meal-plans': typeof AuthenticatedHouseholdsHidMealPlansIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/households/$hid': typeof AuthenticatedHouseholdsHidRouteRouteWithChildren
  '/_authenticated/households/new': typeof AuthenticatedHouseholdsNewRoute
  '/_authenticated/households/': typeof AuthenticatedHouseholdsIndexRoute
  '/_authenticated/households/$hid/archive': typeof AuthenticatedHouseholdsHidArchiveRoute
  '/_authenticated/households/$hid/overview': typeof AuthenticatedHouseholdsHidOverviewRoute
  '/_authenticated/households/$hid/settings': typeof AuthenticatedHouseholdsHidSettingsRoute
  '/_authenticated/households/$hid/freezers/$fid': typeof AuthenticatedHouseholdsHidFreezersFidRoute
  '/_authenticated/households/$hid/items/': typeof AuthenticatedHouseholdsHidItemsIndexRoute
  '/_authenticated/households/$hid/meal-plans/': typeof AuthenticatedHouseholdsHidMealPlansIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/profile'
    | '/households/$hid'
    | '/households/new'
    | '/households/'
    | '/households/$hid/archive'
    | '/households/$hid/overview'
    | '/households/$hid/settings'
    | '/households/$hid/freezers/$fid'
    | '/households/$hid/items/'
    | '/households/$hid/meal-plans/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/profile'
    | '/households/$hid'
    | '/households/new'
    | '/households'
    | '/households/$hid/archive'
    | '/households/$hid/overview'
    | '/households/$hid/settings'
    | '/households/$hid/freezers/$fid'
    | '/households/$hid/items'
    | '/households/$hid/meal-plans'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/profile'
    | '/_authenticated/households/$hid'
    | '/_authenticated/households/new'
    | '/_authenticated/households/'
    | '/_authenticated/households/$hid/archive'
    | '/_authenticated/households/$hid/overview'
    | '/_authenticated/households/$hid/settings'
    | '/_authenticated/households/$hid/freezers/$fid'
    | '/_authenticated/households/$hid/items/'
    | '/_authenticated/households/$hid/meal-plans/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/households/': {
      id: '/_authenticated/households/'
      path: '/households'
      fullPath: '/households/'
      preLoaderRoute: typeof AuthenticatedHouseholdsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/households/new': {
      id: '/_authenticated/households/new'
      path: '/households/new'
      fullPath: '/households/new'
      preLoaderRoute: typeof AuthenticatedHouseholdsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/households/$hid': {
      id: '/_authenticated/households/$hid'
      path: '/households/$hid'
      fullPath: '/households/$hid'
      preLoaderRoute: typeof AuthenticatedHouseholdsHidRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/households/$hid/settings': {
      id: '/_authenticated/households/$hid/settings'
      path: '/settings'
      fullPath: '/households/$hid/settings'
      preLoaderRoute: typeof AuthenticatedHouseholdsHidSettingsRouteImport
      parentRoute: typeof AuthenticatedHouseholdsHidRouteRoute
    }
    '/_authenticated/households/$hid/overview': {
      id: '/_authenticated/households/$hid/overview'
      path: '/overview'
      fullPath: '/households/$hid/overview'
      preLoaderRoute: typeof AuthenticatedHouseholdsHidOverviewRouteImport
      parentRoute: typeof AuthenticatedHouseholdsHidRouteRoute
    }
    '/_authenticated/households/$hid/archive': {
      id: '/_authenticated/households/$hid/archive'
      path: '/archive'
      fullPath: '/households/$hid/archive'
      preLoaderRoute: typeof AuthenticatedHouseholdsHidArchiveRouteImport
      parentRoute: typeof AuthenticatedHouseholdsHidRouteRoute
    }
    '/_authenticated/households/$hid/meal-plans/': {
      id: '/_authenticated/households/$hid/meal-plans/'
      path: '/meal-plans'
      fullPath: '/households/$hid/meal-plans/'
      preLoaderRoute: typeof AuthenticatedHouseholdsHidMealPlansIndexRouteImport
      parentRoute: typeof AuthenticatedHouseholdsHidRouteRoute
    }
    '/_authenticated/households/$hid/items/': {
      id: '/_authenticated/households/$hid/items/'
      path: '/items'
      fullPath: '/households/$hid/items/'
      preLoaderRoute: typeof AuthenticatedHouseholdsHidItemsIndexRouteImport
      parentRoute: typeof AuthenticatedHouseholdsHidRouteRoute
    }
    '/_authenticated/households/$hid/freezers/$fid': {
      id: '/_authenticated/households/$hid/freezers/$fid'
      path: '/freezers/$fid'
      fullPath: '/households/$hid/freezers/$fid'
      preLoaderRoute: typeof AuthenticatedHouseholdsHidFreezersFidRouteImport
      parentRoute: typeof AuthenticatedHouseholdsHidRouteRoute
    }
  }
}

interface AuthenticatedHouseholdsHidRouteRouteChildren {
  AuthenticatedHouseholdsHidArchiveRoute: typeof AuthenticatedHouseholdsHidArchiveRoute
  AuthenticatedHouseholdsHidOverviewRoute: typeof AuthenticatedHouseholdsHidOverviewRoute
  AuthenticatedHouseholdsHidSettingsRoute: typeof AuthenticatedHouseholdsHidSettingsRoute
  AuthenticatedHouseholdsHidFreezersFidRoute: typeof AuthenticatedHouseholdsHidFreezersFidRoute
  AuthenticatedHouseholdsHidItemsIndexRoute: typeof AuthenticatedHouseholdsHidItemsIndexRoute
  AuthenticatedHouseholdsHidMealPlansIndexRoute: typeof AuthenticatedHouseholdsHidMealPlansIndexRoute
}

const AuthenticatedHouseholdsHidRouteRouteChildren: AuthenticatedHouseholdsHidRouteRouteChildren =
  {
    AuthenticatedHouseholdsHidArchiveRoute:
      AuthenticatedHouseholdsHidArchiveRoute,
    AuthenticatedHouseholdsHidOverviewRoute:
      AuthenticatedHouseholdsHidOverviewRoute,
    AuthenticatedHouseholdsHidSettingsRoute:
      AuthenticatedHouseholdsHidSettingsRoute,
    AuthenticatedHouseholdsHidFreezersFidRoute:
      AuthenticatedHouseholdsHidFreezersFidRoute,
    AuthenticatedHouseholdsHidItemsIndexRoute:
      AuthenticatedHouseholdsHidItemsIndexRoute,
    AuthenticatedHouseholdsHidMealPlansIndexRoute:
      AuthenticatedHouseholdsHidMealPlansIndexRoute,
  }

const AuthenticatedHouseholdsHidRouteRouteWithChildren =
  AuthenticatedHouseholdsHidRouteRoute._addFileChildren(
    AuthenticatedHouseholdsHidRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedHouseholdsHidRouteRoute: typeof AuthenticatedHouseholdsHidRouteRouteWithChildren
  AuthenticatedHouseholdsNewRoute: typeof AuthenticatedHouseholdsNewRoute
  AuthenticatedHouseholdsIndexRoute: typeof AuthenticatedHouseholdsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedHouseholdsHidRouteRoute:
    AuthenticatedHouseholdsHidRouteRouteWithChildren,
  AuthenticatedHouseholdsNewRoute: AuthenticatedHouseholdsNewRoute,
  AuthenticatedHouseholdsIndexRoute: AuthenticatedHouseholdsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
