apiVersion: v2
name: freezer-tracker-chart
description: Helm chart for the FreezerMan NestJS backend API
type: application
version: "0.2.6"
appVersion: "0.2.3"
annotations:
  org.opencontainers.image.source: https://github.com/Supporterino/FreezerTracker
  org.opencontainers.image.description: Helm chart for the FreezerMan server
maintainers:
  - name: Supporterino
    url: https://github.com/Supporterino
sources:
  - https://github.com/Supporterino/FreezerTracker
